### ISSUE TITLE
getNumberOfChilds also counts nodes which are commented out

### ISSUE THREAD

**Issue by DaSilber** [DLR-SC/tixi#141]
getNumberOfChilds also counts nodes which are commented out

**Comment by joergbrech** [comment]
This is intentional, a comment is a valid xml node: https://www.w3schools.com/xml/dom_nodetype.asp

This behavior is even checked in the unit tests here: 

https://github.com/DLR-SC/tixi/blob/86b8c78c801203beed48c7c97ee1d30e5564b715/tests/get_element_check.cpp#L232-L236

The unit tests reads in https://github.com/DLR-SC/tixi/blob/master/tests/TestData/in.xml

**Comment by joergbrech** [comment]
@DaSilber, I will close this issue for now. If you still have questions regarding this, feel free to reopen it!
