### ISSUE TITLE
Behavior of function tixiAddTextElementAtIndex wired

### ISSUE THREAD

**Issue by hmkoch88** [DLR-SC/tixi#172]
I use Python 3
Adding at Index 1 replaces instead of adding.
Adding at Index 0 adds at the end.  

Example attached. Expected output will also be generated. 
[tixi_issue_2020-10-19.zip](https://github.com/DLR-SC/tixi/files/5401491/tixi_issue_2020-10-19.zip)

**Comment by rainman110** [comment]
Some notes that I remember from my telefone call with @hmkoch88: 
 - when inserting with tixiAddTextElementAtIndex, the current element at that position will be moved to the end (which is odd but maybe okay)
 - the moved element though seems to be loosing its attributes

We have to discuss two different issues: 
 1) Should when inserting an element at an intermediate position, should that put only the old element to the end or should move all following element move one position?
 2) Why are attributes lost during move?

**Comment by rainman110** [comment]
@hmkoch88  It seems not to be a tixi bug but you are using tixi incorrectly. If you want to insert at the first position, use the index 1 (instead of 0).

The following code demonstrates the problem:

```python
tixi.create('cpacs')
tixi.addTextElement('/cpacs', 'test','MISSING')  
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft1')
tixi.addTextElementAtIndex('/cpacs', 'test', 'MISSING', 0) 
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft2') 
```

This creates the following XML file:
```xml
<?xml version="1.0"?>
<cpacs>
  <test uID="aircraft2">MISSING</test>
  <test>MISSING</test>
</cpacs>
```


It seems, that tixi make an error and forgets the attributes of the first entry. Lets change the code slightly. Then we can see, what is happening really:

```python
tixi.create('cpacs')

tixi.addTextElement('/cpacs', 'test','MISSING1') 
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft1')
tixi.addTextElementAtIndex('/cpacs', 'test', 'MISSING2', 0)
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft2')
```

results in

```xml
<?xml version="1.0"?>
<cpacs>
  <test uID="aircraft2">MISSING1</test>
  <test>MISSING2</test>
</cpacs>
```

That means, the last line replaces the attribute instead of adding the attribute to the correct element. Lets fix it:

```python
tixi.create('cpacs')
tixi.addTextElement('/cpacs', 'test','MISSING1')
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft1')
tixi.addTextElementAtIndex('/cpacs', 'test', 'MISSING2', 1)
tixi.addTextAttribute('/cpacs/test[1]','uID','aircraft2')
```

This results in the desired xml:

```xml
<?xml version="1.0"?>
<cpacs>
  <test uID="aircraft2">MISSING2</test>
  <test uID="aircraft1">MISSING1</test>
</cpacs>
```

**Comment by rainman110** [comment]
@hmkoch88 Can you please change your script accordingly and let me know, whether this issue can be closed?
