### ISSUE TITLE
Save for recursive XML-file leads to access violation

### ISSUE THREAD

**Issue by raedma** [DLR-SC/tixi#175]
I have created a modular CPACS file for a project where I use the python wrapper for tixi. Documents are opened using `tixi.open(test.xml,recursive=True)`.

During the steps of my process a tool tries to save the xml file using `tixi.save(text.xml)`. However, this leads to an access violation. I wrote a small script to demonstrate the problem: [IncludeTest.zip](https://github.com/DLR-SC/tixi/files/5553349/IncludeTest.zip). The output is:

    No such file or directoryNo such file or directoryError:  Can not add element to document. Document already saved.
    Error:  Can not add element to document. Document already saved.
    Error:  Can not add element to document. Document already saved.
    Traceback (most recent call last):
      File "readXML.py", line 58, in <module>
        test()
      File "readXML.py", line 54, in test
        tixi.save(resultfolder + "/Multisplit.xml")
      File "D:\Programme\Miniconda\3\4.7.12\envs\tixi\lib\site-packages\tixi3\tixi3wrapper.py", line 222, in save
        self.saveDocument(fileName)
      File "D:\Programme\Miniconda\3\4.7.12\envs\tixi\lib\site-packages\tixi3\tixi3wrapper.py", line 336, in saveDocument
        errorCode = self.lib.tixiSaveDocument(self._handle, _c_xmlFilename)
    OSError: exception: access violation reading 0x0000000000000030

Is the normal `save` operation not intended for files that are opened using `recursive=true`?

**Comment by joergbrech** [comment]
I can reproduce this. This looks like a bug to me. Thanks for reporting!

**Comment by joergbrech** [comment]
The problem is in this code block:

https://github.com/DLR-SC/tixi/blob/9d51098a57a83f213794dbc4ce25d4c74f0a26e5/src/tixiInternal.c#L841-L846

This code block can only be reached if `cur_node` is an external data node. If *additionally* it is the first child of its parent node, `cur_node->prev` is a null pointer. In the block above `cur_node` gets replaced by `cur_node->prev` which is used in the next iteration of the loop.

## Workaround

This is definitely a bug and needs to be fixed. Until then, you can add a dummy node - which can be a comment - just before your external data node like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<elasticityEvolution name="5b29606d-c2dd-4f86-8594-4e057fb6df44">
  <model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="d57a6369-4b41-4254-8ffd-e895970ff865" xsi:type="constantElasticityEvolutionModel">
    <!-- -->
    <externaldata>
      <path>file://.</path>
      <filename>ElasticityEvolutionValue.xml</filename>
    </externaldata>
  </model>
</elasticityEvolution>
```

**Comment by rainman110** [comment]
I see 2 problems with the current implementation:
 1. The external node is created at the end of the node child block. This potentially changes the order of nodes, which should not happen.
 2. The implemenation itself is error prone and leads to the current bug.

I propose the following fix: Instead of creating the external node with tixiAddTextElement, we should simply create a free node with the libxml api and then swap the external node with the node that should be deleted. This way, the order will remain intact and also we don't have to check for these special cases, when there is no previous node.
